server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pybbs?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: ["classpath:/static/"]

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#logging:
#  level:
#    co:
#      yiiu:
#        pybbs:
#          mapper: debug
